apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  creationTimestamp: "2026-01-18T15:14:06Z"
  finalizers:
    - finalizers.fluxcd.io
  generation: 3
  labels:
    kustomize.toolkit.fluxcd.io/name: chatagent-root
    kustomize.toolkit.fluxcd.io/namespace: dev
  name: chatagent
  namespace: dev
  resourceVersion: "19103929"
  uid: a2a1d379-1930-4906-998d-b217bef96288
spec:
  chartRef:
    kind: OCIRepository
    name: chatagent
  install:
    remediation:
      retries: 3
  interval: 50m
  releaseName: chatagent
  values:
    configs:
      aiclient:
        context_length: 4096
        model: gemini-2.0-flash
        model_provider: google_genai
        stop_sequences: []
        temperature: 1
        timeout: 60
      bot:
        app_id: ""
        app_password: ""
      events:
        checkTime: P0DT0H0M0.500S
        chunkDuration: P0DT0H0M1S
        maxChunks: 100
      hams:
        checks:
          fails: 2
          preflights: []
          shutdowns: []
          timeout: 5
        prefix: hams
        shutdownDuration: P0DT0H0M10S
        url: http://0.0.0.0:8079
      logging:
        disable_existing_loggers: false
        formatters:
          standard:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        handlers:
          console:
            class: logging.StreamHandler
            formatter: standard
            level: INFO
            stream: ext://sys.stdout
        loggers:
          chatagent.hams:
            handlers:
              - console
            level: WARNING
            propagate: false
        root:
          handlers:
            - console
          level: INFO
        version: 1
      myai:
        system_instruction:
          - text: You are a helpful assistant.
        toolbox:
          max_concurrent: 10
          mcps:
            - name: customers
              url: http://customer-mcp/mcp/http/mcp
              transport: streamable_http
          tools:
            - max_instances: 10
              name: sum_numbers
            - max_instances: 10
              name: multiply_numbers
            - max_instances: 10
              name: search_records_by_name
            - max_instances: 10
              name: delete_record_by_id
            - max_instances: 10
              name: get_weather
            - max_instances: 10
              name: get_time
            - max_instances: 10
              name: count_calls
      webservice:
        prefix: pie/v0
        url: http://0.0.0.0:8080
    image:
      pullPolicy: Always
      repository: ghcr.io/polecatworks/chatagent-root-chatagent
      tag: main
    imagePullSecrets:
      - name: dockerconfigjson-ghcr-io
status:
  conditions:
    - lastTransitionTime: "2026-01-23T00:23:37Z"
      message: Helm upgrade succeeded for release dev/chatagent.v9 with chart chatagent@0.2.0-main+d33ddb413281
      observedGeneration: 3
      reason: UpgradeSucceeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2026-01-23T00:23:37Z"
      message: Helm upgrade succeeded for release dev/chatagent.v9 with chart chatagent@0.2.0-main+d33ddb413281
      observedGeneration: 3
      reason: UpgradeSucceeded
      status: "True"
      type: Released
  history:
    - appVersion: 0.2.0
      chartName: chatagent
      chartVersion: 0.2.0-main+d33ddb413281
      configDigest: sha256:18bbe23a7e12843eb847837b6d8495b1249ab65d1e15f495ba951b5be61e0b99
      digest: sha256:00f146172d63c2c9f135eebc61a91189c4f192fc436ee272bdb2b421bfd7e3f0
      firstDeployed: "2026-01-18T15:29:15Z"
      lastDeployed: "2026-01-23T00:23:37Z"
      name: chatagent
      namespace: dev
      ociDigest: sha256:d33ddb41328129337050042e8716f66a3c8de3984e71986c224d3c817d580122
      status: deployed
      version: 9
    - appVersion: 0.2.0
      chartName: chatagent
      chartVersion: 0.2.0-main+12dcbff659ab
      configDigest: sha256:18bbe23a7e12843eb847837b6d8495b1249ab65d1e15f495ba951b5be61e0b99
      digest: sha256:414210536d023c14d804f182a794d5e1a9b919dc31463ca8d83c94b865b0380d
      firstDeployed: "2026-01-18T15:29:15Z"
      lastDeployed: "2026-01-22T22:54:03Z"
      name: chatagent
      namespace: dev
      ociDigest: sha256:12dcbff659ab7613f10a08dd8813a63bc9babeeafdcf1d9757c005af3bd08d42
      status: superseded
      version: 8
  lastAttemptedConfigDigest: sha256:18bbe23a7e12843eb847837b6d8495b1249ab65d1e15f495ba951b5be61e0b99
  lastAttemptedGeneration: 3
  lastAttemptedReleaseAction: upgrade
  lastAttemptedReleaseActionDuration: 760.264346ms
  lastAttemptedRevision: 0.2.0-main+d33ddb413281
  lastAttemptedRevisionDigest: sha256:d33ddb41328129337050042e8716f66a3c8de3984e71986c224d3c817d580122
  observedGeneration: 3
  storageNamespace: dev
